import type { Comment, CommentReply, Platform, Post, Profile } from "@/types"

// Mock posts data
export const mockPosts: Post[] = [
  {
    id: "post1",
    title: "10 Tips for Better Productivity",
    thumbnail: "/placeholder.svg?height=200&width=360",
    platform: "YouTube",
    date: "2 days ago",
    caption:
      "In this video, I share my top 10 productivity tips that have helped me stay focused and get more done. These strategies have transformed my workflow and can help you too!",
    likes: 1245,
    comments: 89,
    views: "24.5K",
    url: "#",
  },
  {
    id: "post2",
    title: "My Morning Routine Revealed",
    thumbnail: "/placeholder.svg?height=200&width=360",
    platform: "Instagram",
    date: "5 days ago",
    caption:
      "Ever wondered how I start my day? Here's a behind-the-scenes look at my morning routine that sets me up for success every day.",
    likes: 3782,
    comments: 156,
    views: "42.1K",
    url: "#",
  },
  {
    id: "post3",
    title: "Why I Switched to This Camera",
    thumbnail: "/placeholder.svg?height=200&width=360",
    platform: "YouTube",
    date: "1 week ago",
    caption:
      "After years of using my old setup, I finally made the switch to this camera. Here's why I made the change and my honest review after using it for a month.",
    likes: 876,
    comments: 64,
    views: "18.9K",
    url: "#",
  },
]

// Mock comments data
export const mockComments: Comment[] = [
  {
    id: "comment1",
    author: {
      name: "Alex Johnson",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    text: "This video was exactly what I needed! Your productivity tips have already helped me organize my day better. Can't wait to see more content like this!",
    platform: "youtube",
    time: "2 hours ago",
    timeTooltip: "Today at 1:45 PM",
    likes: 24,
    replies: 3,
    flagged: false,
    needsAttention: false,
    archived: false,
    postId: "post1",
    postTitle: "10 Tips for Better Productivity",
    postThumbnail: "/placeholder.svg?height=40&width=40",
    emotion: "excited",
    sentiment: "positive",
    category: "general",
    isAiGenerated: true,
  },
  {
    id: "comment2",
    author: {
      name: "Sarah Miller",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    text: "I disagree with tip #7. It might work for some people, but it's definitely not a one-size-fits-all solution. Would love to hear your thoughts on alternatives.",
    platform: "youtube",
    time: "5 hours ago",
    timeTooltip: "Today at 10:30 AM",
    likes: 8,
    replies: 1,
    flagged: false,
    needsAttention: true,
    archived: false,
    postId: "post1",
    postTitle: "10 Tips for Better Productivity",
    postThumbnail: "/placeholder.svg?height=40&width=40",
    emotion: "curious",
    sentiment: "negative",
    category: "product",
  },
  {
    id: "comment3",
    author: {
      name: "Mike Thompson",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    text: "Have you tried the Pomodoro technique? I'd love to see a video specifically about that method and how you would implement it.",
    platform: "youtube",
    time: "1 day ago",
    timeTooltip: "Yesterday at 3:15 PM",
    likes: 42,
    replies: 5,
    flagged: false,
    needsAttention: false,
    archived: false,
    postId: "post1",
    postTitle: "10 Tips for Better Productivity",
    postThumbnail: "/placeholder.svg?height=40&width=40",
    emotion: "curious",
    sentiment: "neutral",
    category: "product",
  },
  {
    id: "comment4",
    author: {
      name: "Emily Chen",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    text: "Your morning routine is so inspiring! I've been trying to wake up earlier but struggle with consistency. Any tips for making it a habit?",
    platform: "instagram",
    time: "3 days ago",
    timeTooltip: "Monday at 9:20 AM",
    likes: 15,
    replies: 2,
    flagged: false,
    needsAttention: false,
    archived: false,
    postId: "post2",
    postTitle: "My Morning Routine Revealed",
    postThumbnail: "/placeholder.svg?height=40&width=40",
    emotion: "excited",
    sentiment: "positive",
    category: "general",
    isAiGenerated: true,
  },
  {
    id: "comment5",
    author: {
      name: "David Wilson",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    text: "This is complete garbage. You're just copying other creators and pretending these are your original ideas. Unsubscribed!",
    platform: "youtube",
    time: "4 days ago",
    timeTooltip: "Sunday at 7:45 PM",
    likes: 3,
    replies: 7,
    flagged: true,
    needsAttention: true,
    archived: false,
    postId: "post1",
    postTitle: "10 Tips for Better Productivity",
    postThumbnail: "/placeholder.svg?height=40&width=40",
    emotion: "angry",
    sentiment: "negative",
    category: "spam",
  },
  {
    id: "comment6",
    author: {
      name: "Jessica Lee",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    text: "What camera settings do you use for indoor shots? The lighting in your videos is always perfect!",
    platform: "youtube",
    time: "6 days ago",
    timeTooltip: "Last Friday at 2:30 PM",
    likes: 28,
    replies: 1,
    flagged: false,
    needsAttention: false,
    archived: true,
    postId: "post3",
    postTitle: "Why I Switched to This Camera",
    postThumbnail: "/placeholder.svg?height=40&width=40",
    emotion: "curious",
    sentiment: "positive",
    category: "product",
  },
  {
    id: "comment7",
    author: {
      name: "Ryan Garcia",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    text: "I bought this camera because of your recommendation and I'm so disappointed. The battery life is terrible and the image quality isn't as good as you claimed.",
    platform: "youtube",
    time: "1 week ago",
    timeTooltip: "Last Thursday at 11:15 AM",
    likes: 5,
    replies: 2,
    flagged: false,
    needsAttention: true,
    archived: false,
    postId: "post3",
    postTitle: "Why I Switched to This Camera",
    postThumbnail: "/placeholder.svg?height=40&width=40",
    emotion: "angry",
    sentiment: "negative",
    category: "product",
    isAiGenerated: true,
  },
  {
    id: "comment8",
    author: {
      name: "Olivia Brown",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    text: "Your content has been so helpful for me as I start my own channel. Would you ever consider doing one-on-one coaching sessions?",
    platform: "instagram",
    time: "1 week ago",
    timeTooltip: "Last Wednesday at 4:50 PM",
    likes: 37,
    replies: 1,
    flagged: false,
    needsAttention: false,
    archived: false,
    postId: "post2",
    postTitle: "My Morning Routine Revealed",
    postThumbnail: "/placeholder.svg?height=40&width=40",
    emotion: "happy",
    sentiment: "positive",
    category: "vip",
  },
  {
    id: "comment9",
    author: {
      name: "Chris Taylor",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    text: "I've been following your channel for years and the quality just keeps getting better. This camera upgrade was definitely worth it - the footage looks amazing!",
    platform: "youtube",
    time: "1 week ago",
    timeTooltip: "Last Tuesday at 9:30 AM",
    likes: 52,
    replies: 0,
    flagged: false,
    needsAttention: false,
    archived: false,
    postId: "post3",
    postTitle: "Why I Switched to This Camera",
    postThumbnail: "/placeholder.svg?height=40&width=40",
    emotion: "excited",
    sentiment: "positive",
    category: "vip",
  },
  {
    id: "comment10",
    author: {
      name: "Sophia Martinez",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    text: "Do you have any recommendations for productivity apps that sync across devices? I'm trying to streamline my workflow between my phone and laptop.",
    platform: "youtube",
    time: "1 week ago",
    timeTooltip: "Last Monday at 3:15 PM",
    likes: 19,
    replies: 3,
    flagged: false,
    needsAttention: false,
    archived: false,
    postId: "post1",
    postTitle: "10 Tips for Better Productivity",
    postThumbnail: "/placeholder.svg?height=40&width=40",
    emotion: "curious",
    sentiment: "neutral",
    category: "general",
  },
]

// Mock replies data
export const mockReplies: Record<string, CommentReply[]> = {
  comment1: [
    {
      id: "reply1",
      author: {
        name: "You",
        avatar: "/placeholder.svg?height=32&width=32",
        isOwner: true,
      },
      text: "Thank you so much for your kind words! I'm glad the productivity tips were helpful. I'll be sharing more content like this soon!",
      time: "1 hour ago",
      timeTooltip: "Today at 2:45 PM",
      likes: 3,
      isAiGenerated: true,
    },
    {
      id: "reply2",
      author: {
        name: "Alex Johnson",
        avatar: "/placeholder.svg?height=32&width=32",
      },
      text: "Looking forward to it! Your content is always so helpful.",
      time: "45 minutes ago",
      timeTooltip: "Today at 3:00 PM",
      likes: 1,
    },
  ],
  comment2: [
    {
      id: "reply1",
      author: {
        name: "You",
        avatar: "/placeholder.svg?height=32&width=32",
        isOwner: true,
      },
      text: "That's a fair point! Tip #7 definitely works better for some people than others. I'll make a follow-up video with alternative approaches.",
      time: "4 hours ago",
      timeTooltip: "Today at 11:30 AM",
      likes: 2,
      isAiGenerated: true,
    },
  ],
  comment3: [
    {
      id: "reply1",
      author: {
        name: "You",
        avatar: "/placeholder.svg?height=32&width=32",
        isOwner: true,
      },
      text: "Great suggestion! I've actually been using the Pomodoro technique for years. I'll definitely make a dedicated video about it soon.",
      time: "20 hours ago",
      timeTooltip: "Yesterday at 7:15 PM",
      likes: 8,
    },
    {
      id: "reply2",
      author: {
        name: "Mike Thompson",
        avatar: "/placeholder.svg?height=32&width=32",
      },
      text: "Awesome, can't wait to see it!",
      time: "19 hours ago",
      timeTooltip: "Yesterday at 8:30 PM",
      likes: 2,
    },
    {
      id: "reply3",
      author: {
        name: "Sarah Wilson",
        avatar: "/placeholder.svg?height=32&width=32",
      },
      text: "I'd love to see that too. The Pomodoro technique changed my work habits completely.",
      time: "18 hours ago",
      timeTooltip: "Yesterday at 9:45 PM",
      likes: 3,
    },
  ],
  comment4: [
    {
      id: "reply1",
      author: {
        name: "You",
        avatar: "/placeholder.svg?height=32&width=32",
        isOwner: true,
      },
      text: "Consistency is definitely the hardest part! Try setting your alarm for the same time every day and put it across the room so you have to get up to turn it off. After a couple of weeks, it becomes much easier!",
      time: "2 days ago",
      timeTooltip: "Monday at 10:15 AM",
      likes: 5,
      isAiGenerated: true,
    },
  ],
  comment6: [
    {
      id: "reply1",
      author: {
        name: "You",
        avatar: "/placeholder.svg?height=32&width=32",
        isOwner: true,
      },
      text: "For indoor shots, I use f/2.8, ISO 400, and a shutter speed of 1/60. I also have two softbox lights positioned at 45-degree angles. I'll do a lighting setup tutorial soon!",
      time: "5 days ago",
      timeTooltip: "Last Friday at 3:20 PM",
      likes: 12,
    },
  ],
  comment7: [
    {
      id: "reply1",
      author: {
        name: "You",
        avatar: "/placeholder.svg?height=32&width=32",
        isOwner: true,
      },
      text: "I'm really sorry to hear about your experience. The battery life can be improved with some settings adjustments. Please email me directly and I'll help troubleshoot the issues you're having.",
      time: "6 days ago",
      timeTooltip: "Last Thursday at 2:10 PM",
      likes: 3,
      isAiGenerated: true,
    },
    {
      id: "reply2",
      author: {
        name: "Ryan Garcia",
        avatar: "/placeholder.svg?height=32&width=32",
      },
      text: "Thanks, I'll send you an email today.",
      time: "6 days ago",
      timeTooltip: "Last Thursday at 4:45 PM",
      likes: 1,
    },
  ],
  comment8: [
    {
      id: "reply1",
      author: {
        name: "You",
        avatar: "/placeholder.svg?height=32&width=32",
        isOwner: true,
      },
      text: "I'm so glad my content has been helpful! I'm actually planning to launch coaching sessions next month. I'll announce all the details soon!",
      time: "5 days ago",
      timeTooltip: "Last Friday at 11:30 AM",
      likes: 8,
    },
  ],
  comment10: [
    {
      id: "reply1",
      author: {
        name: "You",
        avatar: "/placeholder.svg?height=32&width=32",
        isOwner: true,
      },
      text: "I personally use Notion for notes and tasks, and it syncs beautifully across all devices. For quick notes, Google Keep is fantastic. Both have great mobile apps!",
      time: "6 days ago",
      timeTooltip: "Last Thursday at 9:15 AM",
      likes: 7,
    },
    {
      id: "reply2",
      author: {
        name: "Sophia Martinez",
        avatar: "/placeholder.svg?height=32&width=32",
      },
      text: "Thanks! I'll check out Notion. I've been using Evernote but looking for something better.",
      time: "6 days ago",
      timeTooltip: "Last Thursday at 10:30 AM",
      likes: 2,
    },
    {
      id: "reply3",
      author: {
        name: "You",
        avatar: "/placeholder.svg?height=32&width=32",
        isOwner: true,
      },
      text: "Notion is definitely worth trying! The learning curve is a bit steeper than Evernote, but the flexibility is amazing.",
      time: "5 days ago",
      timeTooltip: "Last Friday at 8:45 AM",
      likes: 3,
      isAiGenerated: true,
    },
  ],
}

// Platform information
export const platformInfo: Record<Platform, { color: string; icon: string }> = {
  youtube: { color: "youtube", icon: "/youtube.svg" },
  instagram: { color: "instagram", icon: "/instagram.svg" },
  twitter: { color: "twitter", icon: "/twitter.svg" },
  tiktok: { color: "tiktok", icon: "/tiktok.svg" },
  facebook: { color: "facebook", icon: "/facebook.svg" },
  linkedin: { color: "linkedin", icon: "/linkedin.svg" },
}

// Emotion information
export const emotionInfo: Record<string, { icon: string; color: string }> = {
  excited: { icon: "🤩", color: "yellow-500" },
  angry: { icon: "😡", color: "destructive" },
  curious: { icon: "🤔", color: "blue-500" },
  happy: { icon: "😊", color: "green-500" },
  sad: { icon: "😢", color: "blue-500" },
  neutral: { icon: "😐", color: "gray-500" },
}

// Filter options
export const statusFilters = [
  { id: "all", label: "All", icon: "🔍" },
  { id: "flagged", label: "Flagged", icon: "🚩" },
  { id: "attention", label: "Attention", icon: "⚠️" },
  { id: "archived", label: "Archived", icon: "📦" },
]

export const platformFilters = [
  { id: "youtube", label: "YouTube", color: "youtube", icon: "/youtube.svg" },
  { id: "instagram", label: "Instagram", color: "instagram", icon: "/instagram.svg" },
  { id: "twitter", label: "X", color: "twitter", icon: "/twitter.svg" },
  { id: "tiktok", label: "TikTok", color: "tiktok", icon: "/tiktok.svg" },
  { id: "facebook", label: "Facebook", color: "facebook", icon: "/facebook.svg" },
  { id: "linkedin", label: "LinkedIn", color: "linkedin", icon: "/linkedin.svg" },
]

export const emotionFilters = [
  { id: "excited", label: "Excited", icon: "🤩", color: "yellow-500" },
  { id: "angry", label: "Angry", icon: "😡", color: "destructive" },
  { id: "curious", label: "Curious", icon: "🤔", color: "blue-500" },
  { id: "happy", label: "Happy", icon: "😊", color: "green-500" },
  { id: "sad", label: "Sad", icon: "😢", color: "blue-500" },
]

export const sentimentFilters = [
  { id: "positive", label: "Positive", icon: "👍", color: "green-500" },
  { id: "negative", label: "Negative", icon: "👎", color: "destructive" },
  { id: "neutral", label: "Neutral", icon: "🤷", color: "gray-500" },
]

export const categoryFilters = [
  { id: "product", label: "Product Feedback", icon: "💬", color: "blue-500" },
  { id: "vip", label: "VIP", icon: "⭐", color: "yellow-500" },
  { id: "spam", label: "Spam", icon: "🚫", color: "red-500" },
  { id: "general", label: "General", icon: "📦", color: "gray-500" },
]

// Mock user profile
export const mockProfile: Profile = {
  id: 'mock-user-1',
  teamId: 'mock-team',
  userName: 'Mock User',
  email: 'mock@pulsepilot.com',
  avatarUrl: '/placeholder.svg?height=80&width=80',
  roles: ['admin'],
  settings: {},
}
